language: rust
before_install:
    - sudo apt-get install -y libfuse-dev
script:
    - cargo build
    - cargo run --bin=day2
    - cargo run --bin=day3
    - cargo run --bin=day4
    - cargo run --bin=day5
    - cargo run --bin=day6
    - cargo run --bin=day7
    - cargo run --bin=day9
    - cargo run --bin=day10
    - cargo run --bin=day11
    - cargo run --bin=day12
    - cargo run --bin=day13
#   - cargo run --bin=day14
#   - cargo run --bin=day17
    - cargo run --bin=day18
    - cargo run --bin=day21
services:
    - redis-server
