environment:
    OPENSSL_INCLUDE_DIR: C:\OpenSSL-Win32\include
    OPENSSL_LIB_DIR: C:\OpenSSL-Win32\lib
    OPENSSL_LIBS: ssleay32:libeay32

install:
    - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-gnu.exe'
    - rust-nightly-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
    - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin;C:\MinGW\bin;C:\OpenSSL-Win32
    - gcc --version
    - rustc -V
    - cargo -V

build: false

test_script:
    - cargo build
