[package]

name = "24daysofrust"
version = "0.0.1"
authors = ["Zbigniew Siciarz <zbigniew@siciarz.net>"]

#[[bin]]
#name = "day2"

[[bin]]
name = "day3"

[[bin]]
name = "day4"

[[bin]]
name = "day5"

[[bin]]
name = "day6"

[[bin]]
name = "day7"

[[bin]]
name = "day9"

[[bin]]
name = "day10"

[[bin]]
name = "day11"

[[bin]]
name = "day12"

[[bin]]
name = "day13"

[[bin]]
name = "day14"

[[bin]]
name = "day15"

[[bin]]
name = "day17"

[[bin]]
name = "day18"

#[[bin]]
#name = "day20"

[[bin]]
name = "day21"

[dependencies]
anymap = "~0.10.0"
csv = "~0.13.7"
docopt = "~0.6.59"
docopt_macros = "~0.6.59"
hyper = "~0.3.8"
image = "~0.3.4"
itertools = "~0.2.3"
json_macros = "~0.2.2"
num = "~0.1.20"
postgres_array = "~0.4.0"
postgres_macros = "~0.1.1"
rand = "~0.3.7"
redis = "~0.2.0"
rust-crypto = "~0.2.30"
rustc-serialize = "~0.3.12"
#slow_primes = "~0.1.11"
time = "~0.1.24"
tau = "~1.0.2"
url = "~0.2.28"
uuid = "~0.1.15"


[dependencies.postgres]
version= "~0.8.1"
features = ["rustc-serialize"]

[dependencies.fuse]
git = "https://github.com/zargony/rust-fuse.git"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra.git"

#[dependencies.zeromq]
#git = "https://github.com/zeromq/zmq.rs.git"
