[package]

name = "24daysofrust"
version = "0.0.1"
authors = ["Zbigniew Siciarz <zbigniew@siciarz.net>"]

[[bin]]
name = "day2"

[[bin]]
name = "day3"

[[bin]]
name = "day4"

[[bin]]
name = "day5"

[[bin]]
name = "day6"

[[bin]]
name = "day7"

[[bin]]
name = "day9"

[[bin]]
name = "day10"

[[bin]]
name = "day11"

[[bin]]
name = "day12"

[[bin]]
name = "day13"

[[bin]]
name = "day14"

[[bin]]
name = "day15"

[[bin]]
name = "day17"

#[[bin]]
#name = "day18"

#[[bin]]
#name = "day20"

[[bin]]
name = "day21"

[dependencies]
anymap = "~0.9.10"
csv = "~0.12.16"
docopt = "~0.6.37"
docopt_macros = "~0.6.37"
hyper = "~0.1.12"
itertools = "~0.1.4"
json_macros = "~0.2.0"
num = "~0.1.12"
postgres = "~0.6.2"
postgres_array = "~0.2.1"
postgres_macros = "~0.0.6"
rand = "~0.1.2"
#redis = "~0.0.5"
rust-crypto = "~0.2.16"
rustc-serialize = "~0.2.12"
slow_primes = "~0.1.9"
time = "~0.1.17"
tau = "~1.0.1"
url = "~0.2.20"
uuid = "~0.1.9"

[dependencies.fuse]
git = "https://github.com/zargony/rust-fuse.git"

[dependencies.image]
git = "https://github.com/PistonDevelopers/image"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra.git"

#[dependencies.zeromq]
#git = "https://github.com/zeromq/zmq.rs.git"
