[package]
name = "24daysofrust_vol2"
version = "0.0.1"
authors = ["Zbigniew Siciarz <zbigniew@siciarz.net>"]

[[bin]]
name = "day2"

[[bin]]
name = "day3"

[[bin]]
name = "day4"

[[bin]]
name = "day5"

[[bin]]
name = "day6"

[[bin]]
name = "day7"

[[bin]]
name = "day8"

[[bin]]
name = "day9"

[[bin]]
name = "day10"

[[bin]]
name = "day11"

[[bin]]
name = "day12"

[[bin]]
name = "day13"

[[bin]]
name = "day14"

[[bin]]
name = "day15"

[[bin]]
name = "day16"

[[bin]]
name = "day17"

[[bin]]
name = "day18"

[[bin]]
name = "day19"

[[bin]]
name = "day20"

[[bin]]
name = "day21"

#[[bin]]
#name = "day22"

[dependencies]
app_dirs = "1.1.1"
clap = "2.20.0"
custom_derive = "0.1.7"
derive_builder = "0.2.1"
dotenv = "0.8.0"
envy = "0.1.2"
error-chain = "0.8.1"
hound = "3.0.0"
lazy_static = "0.2.2"
leftpad = "0.2.0"
#lettre = "0.6.1"
markdown = "0.2.0"
nom = "2.1.0"
num = "0.1.36"
num_cpus = "1.2.1"
preferences = "0.7.3"
phf = "0.7.21"
phf_macros = "0.7.21"
rand = "0.3.14"
rayon = "0.6.0"
reqwest = "0.4.0"
rustc-serialize = "0.3.22"
rustfft = "1.0.1"
serde = "0.9.5"
serde_derive = "0.9.5"
serde_json = "0.9.3"
serde_yaml = "0.6.0"
slog = "1.4.1"
slog-json = "1.2.1"
slog-stream = "1.2.0"
slog-term = "1.4.0"
tempfile = "2.1.5"
tera = "0.7.0"
time = "0.1.36"
uuid = { version = "0.3.1", features = ["v4"] }
zip = "0.2.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.4"

[target.'cfg(unix)'.dependencies]
cursive = { git = "https://github.com/gyscos/Cursive", default-features = false, features=["pancurses"] }
diesel = "0.9.1"
diesel_codegen = { version = "0.9.0", features=["postgres"]}
git2 = "0.6.4"
rust-lzma = "0.2.1"
