[package]
name = "24daysofrust_vol2"
version = "0.0.1"
authors = ["Zbigniew Siciarz <zbigniew@siciarz.net>"]

[[bin]]
name = "day2"

[[bin]]
name = "day3"

[[bin]]
name = "day4"

[[bin]]
name = "day5"

[dependencies]
dotenv = "0.8.0"
envy = "0.1.2"
hound = "2.0.0"
num = "0.1.36"
num_cpus = "1.1.0"
rand = "0.3.14"
rayon = "0.5.0"
rustfft = "1.0.1"
serde = "0.8.19"
serde_derive = "0.8.19"
slog = "1.3.2"
slog-json = "1.2.1"
slog-stream = "1.2.0"
slog-term = "1.3.3"
time = "0.1.35"
